version: '3'
services:
  rest-api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    hostname: rest-api
    ports:
      - "3000:3000"
    networks:
      - web

networks:
  web:
    driver: bridge